--------------------------------------------------------
--  Fichier créé - vendredi-novembre-09-2018   
--------------------------------------------------------
DROP TABLE "SALAFIN"."RECRUTEUR";
--------------------------------------------------------
--  DDL for Table RECRUTEUR
--------------------------------------------------------

  CREATE TABLE "SALAFIN"."RECRUTEUR" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"DEPTID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SALAFIN.RECRUTEUR
SET DEFINE OFF;
Insert into SALAFIN.RECRUTEUR (ID,NAME,DEPTID) values ('101202303','mourad boussalmi','orus services');
Insert into SALAFIN.RECRUTEUR (ID,NAME,DEPTID) values ('783432188','Adrian Jones','MGT');
Insert into SALAFIN.RECRUTEUR (ID,NAME,DEPTID) values ('121232343','David Jones','EE');
Insert into SALAFIN.RECRUTEUR (ID,NAME,DEPTID) values ('864297531','Qi Chen','MAT');
Insert into SALAFIN.RECRUTEUR (ID,NAME,DEPTID) values ('555666777','Mary Doe','CS');
Insert into SALAFIN.RECRUTEUR (ID,NAME,DEPTID) values ('9406321','Jacob Taylor','MGT');
Insert into SALAFIN.RECRUTEUR (ID,NAME,DEPTID) values ('900120450','Ann White','MAT');
--------------------------------------------------------
--  DDL for Index PK_RECRUTEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAFIN"."PK_RECRUTEUR" ON "SALAFIN"."RECRUTEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RECRUTEUR
--------------------------------------------------------

  ALTER TABLE "SALAFIN"."RECRUTEUR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SALAFIN"."RECRUTEUR" ADD CONSTRAINT "PK_RECRUTEUR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
